select T1.*,T3.Junior_Buyer from DXWV_PROD_UK_VIEW_ACCESS.VWV0LWJ_WK_IT_LS_SUPP T1
INNER JOIN DXWV_PROD_UK_VIEW_ACCESS.VWI0BPR_BASE_PRODUCT AS T2
ON T1.Item_L2_SKU=T2.Base_Product_Number
INNER JOIN DXWI_PROD_VIEW_ACCESS.VWI0BUY_DAILY_BUYER_LOOKUP AS T3
ON T2.Product_Sub_Group_Code=T3.Product_Sub_Group_Code
where Supplier=46161 and  Year_Week_Number between 201912 and 202008